module.exports = {
  'no-empty-function': 'error',
  'no-unused-expressions': 'warn',
  'no-use-before-define': 'off',
  'no-unused-vars': ['error', {
    'ignoreRestSiblings': true,
    'argsIgnorePattern': '^_',
  }],
  'quotes': [
    'error',
    'single',
  ],
  'require-await': 'error',
  'semi': [
    'error',
    'never',
  ],
  'comma-dangle': [
    'error',
    {
      'objects': 'always-multiline',
      'arrays': 'always-multiline',
      'functions': 'always-multiline',
      'imports': 'always-multiline',
      'exports': 'always-multiline',
    },
  ],
  'complexity': 'off',
  'constructor-super': 'error',
  'curly': [
    'error',
    'all',
  ],
  'eqeqeq': [
    'error',
    'smart',
  ],
  'id-blacklist': [
    'error',
    'any',
    'Number',
    'number',
    'String',
    'string',
    'Boolean',
    'boolean',
    'Undefined',
    'undefined',
  ],
  'import/no-extraneous-dependencies': 'off',
  'import/no-default-export': 'error',
  'import/order': 'off',
  'max-classes-per-file': 'off',
  'max-len': [
    'error',
    {
      'ignoreRegExpLiterals': true,
      'ignoreStrings': true,
      'ignoreComments': true,
      'ignoreUrls': true,
      'code': 120,
    },
  ],
  'keyword-spacing': [
    'error',
    {
      'before': true,
      'after': true,
    },
  ],
  'key-spacing': [
    'error',
    {
      'afterColon': true,
    },
  ],
  'space-before-blocks': ['error', 'always'],
  'object-curly-spacing': ['error', 'always'],
  'no-multiple-empty-lines': 'error',
  'space-infix-ops': 'error',
  'new-parens': 'error',
  'no-bitwise': 'off',
  'no-caller': 'error',
  'no-cond-assign': 'error',
  'no-console': 'error',
  'no-debugger': 'off',
  'no-duplicate-case': 'error',
  'no-duplicate-imports': 'error',
  'no-empty': 'error',
  'no-eval': 'error',
  'no-extra-bind': 'error',
  'no-fallthrough': 'off',
  'no-invalid-this': 'off',
  'no-new-func': 'error',
  'no-new-wrappers': 'error',
  'no-redeclare': 'error',
  'no-return-await': 'error',
  'no-sequences': 'error',
  'no-sparse-arrays': 'error',
  'no-template-curly-in-string': 'error',
  'no-throw-literal': 'error',
  'no-trailing-spaces': 'error',
  'no-undef-init': 'error',
  'no-unsafe-finally': 'error',
  'no-unused-labels': 'error',
  'no-var': 'error',
  'object-shorthand': 'error',
  'one-var': [
    'error',
    'never',
  ],
  'prefer-const': 'error',
  'prefer-object-spread': 'error',
  'radix': 'error',
  'space-in-parens': [
    'error',
    'never',
  ],
  'spaced-comment': [
    'error',
    'always',
    {
      'markers': [
        '/',
      ],
    },
  ],
  'no-unneeded-ternary': 'error',
  'use-isnan': 'error',
  'valid-typeof': 'off',
  'yoda': ['error', 'never'],
  'space-before-function-paren': ['error', {
    'anonymous': 'always',
    'named': 'never',
    'asyncArrow': 'always',
  }],
  'arrow-spacing': 'error',
  'spaced-comment': 'error',
  'no-multi-spaces': 'error',
}
